config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :products
  resources :clients

  root to: 'dashboard#index', as: 'dashboard'

  get 'info', to: 'info#index' 

end

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates :client, :product, presence: true
	validates :quantity, presence: true, numericality: {greater_than_or_equal_to: 1}
	
	belongs_to :product
	belongs_to :client
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @clients = Client.order("description").all
    @products = Product.order("title").all
  end

  # GET /sales/1/edit
  def edit
    @clients = Client.order("description").all
    @products = Product.order("title").all
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:client_id, :product_id, :quantity)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= select("sale", "client_id", @clients.collect {|c| [ c.description, c.id ] }) %>
  </div>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= select("sale", "product_id", @products.collect {|p| [ p.title, p.id ] }) %>  
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary fa' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to ' Show', @sale %> |
<%= link_to ' Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<div class="panel panel-default">
  <div class="panel-heading">Sales (<%= @sales.count %>) </div>
    <table class="table table-hover">

      <thead>
        <tr>
          <th>#</th>
          <th>Client</th>
          <th>Product</th>          
          <th>Quantity</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% i = 0%>
        <% @sales.each do |sale| %>
          <tr>
            <th><%= i += 1 %></th>
            <td><%= Client.find(sale.client).description %></td>
            <td><%= Product.find(sale.product).title %></td>
            <td><%= sale.quantity %></td>
            <td>
              <%= fa_icon "info" %>
              <%= link_to 'Show', sale %>
              |
              <%= fa_icon "pencil-square-o" %>
              <%= link_to 'Edit', edit_sale_path(sale) %>
              |
              <%= fa_icon "trash-o" %>
              <%= link_to 'Delete', sale, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

<%= link_to ' New Sale', new_sale_path, :class => 'btn btn-primary fa fa-plus' %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to ' Back', sales_path, :class => 'btn btn-primary fa fa-arrow-left' %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= Product.find(@sale.product).title %>
</p>

<p>
  <strong>Client:</strong>
  <%= Client.find(@sale.client).description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @sale.quantity %>
</p>

<%= link_to ' Edit', edit_sale_path(@sale) %> |
<%= link_to ' Back', sales_path %>