config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :products
  resources :clients

  root to: 'dashboard#index', as: 'dashboard'

  get 'info', to: 'info#index' 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mountt - improve your business</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Analytic system for small business">
  <meta name="robots" content="index,follow">
  <meta name="google-site-verification" content="T1M_NJ5x0EZcX0214A2OQCZM8yjoVzUaY6gyEq_yTkY" />
</head>
<body>
    
    <nav class="sidebar">
        <div class="brand">
            <%= link_to image_tag("logo.png"), '/' %>
        </div>
        <div class="menu">
            <ul>
                <li> 
                    <%= fa_icon "bar-chart" %>
                    <%= link_to t(:dashboard), dashboard_path %>
                </li>
                <li>
                    <%= fa_icon "user" %>
                    <%= link_to t(:clients), clients_path %>
                </li>
                <li>
                    <%= fa_icon "money" %>
                    <%= link_to t(:sales), sales_path %>
                </li>
                <li>
                    <%= fa_icon "cubes" %>
                    <%= link_to t(:products), products_path %>
                </li>
                <li>
                    <%= fa_icon "paper-plane" %>
                    <%= link_to t(:plans), dashboard_path %>
                </li>
                <li>
                    <%= fa_icon "info" %>
                    <%= link_to 'Info', info_path %>
                </li>
            </ul>
        </div>
        <div class="copyright">
            © 2015 Roman Krasavtsev
        </div>
    </nav>

    <nav class="navbar">
        <div class="left">
            <button id="menu-button" type="button" class="btn btn-primary" aria-label="Left Align">
                <%= fa_icon "bars" %>
            </button>
        </div>
        <div class="right">
            <div class="welcome">
                <%= t(:welcome) %> Mountt, 
                <span class="username">Roman Krasavtsev</span>
            </div>
            <div class="language">
                <%= fa_icon "globe" %>
                <%= t(:language) %>
            </div>
            <div class="logout">
                <%= fa_icon "sign-out" %>
                <%= t(:logout) %>
            </div>
        </div>
    </nav>

    <div class="main-panel">
        <div class='<%= controller.controller_name %>'>
            <%= yield %>
        </div>
    </div>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-33202498-4', 'auto');
        ga('send', 'pageview');
    </script>
</body>
</html>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter32207004 = new Ya.Metrika({id:32207004, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/32207004" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->